ersion = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "empirica-case"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rh99n4n65836"
s3_prefix = "empirica-case"
region = "us-east-1"
profile = "pessoal"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "DeployStage=\"homolog\" CessaoS3Bucket=\"empirica-cessao-arquivos\" ApiVersion=\"V1\""
image_repositories = []
